namespace EFDemoConsoleApp.Models;

// READ 8.
// The User entity represents a row in the Users table.
// - Id: GUID primary key, generated by the database
// - Email: User's email address, unique and required
// EF Core maps this class to a database table using conventions and Fluent API configuration.
// Proceed to READ 9 in \Data\AppDbContext.cs
public class User
{
    public Guid Id { get; set; }
    public string Email { get; set; } = string.Empty;
}