using EFDemoConsoleApp.Models;
using Microsoft.EntityFrameworkCore;

namespace EFDemoConsoleApp.Data;

// READ 5.
// DbContext is the primary class for interacting with the database in Entity Framework Core.
// It manages the database connection and provides methods for querying and saving data.
// The connection string is injected through the constructor via dependency injection.
public class AppDbContext : DbContext
{
    // READ 6.
    // Constructor accepts DbContextOptions which contains the connection string and provider configuration.
    // This is injected by the dependency injection container at runtime.
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
        // Not doing anything besides passing options to base class.
    }

    // READ 7.
    // DbSet represents a collection of entities that can be queried from the database.
    // It allows us to perform CRUD operations on the User table.
    // Proceed to READ 8 in \Models\User.cs
    public DbSet<User> Users { get; set; }

    // READ 9.
    // OnModelCreating configures the database schema using Fluent API.
    // This defines how the User model maps to the database table.
    // - Id is the primary key, auto-generated by SQL Server using NEWID()
    // - Email is required, max 255 characters, and must be unique
    // Proceed to READ 10 in Program.cs
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).HasDefaultValueSql("NEWID()");
            entity.Property(e => e.Email).IsRequired().HasMaxLength(255);
            entity.HasIndex(e => e.Email).IsUnique();
        });
    }
}